### ISSUE TITLE
Issue on convert Pytorch to ONNX model

### ISSUE THREAD

**Issue by liukaigua** [CaoWGG/TensorRT-CenterNet#14]
Hi, 
Thank you for your [convert code](https://github.com/CaoWGG/TensorRT-CenterNet/issues/1#issuecomment-549097594), it did help me.However, when I use [onnxruntime](https://github.com/microsoft/onnxruntime) to load the onnx model just converted, an error arises. My code refers to the [official tutorial](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html).
```
import onnxruntime
import torch
import numpy as np

ort_session = onnxruntime.InferenceSession('../models/ctdet_coco_dlav0_1x.onnx')

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
    
x = torch.randn(1, 3, 224, 224, requires_grad=True)
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort.session.run(None, ort.inputs)
print(ort_outs)
```
And the error is like this.
```
2019-12-14 03:23:15.906272817 [W:onnxruntime:Default, model.cc:114 Model] ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher. For now, this opset 6 model may run depending upon legacy support of some older opset version operators.
...
2019-12-14 03:23:15.911351190 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer '192'. It is not used by any node and should be removed from the model.
2019-12-14 03:23:15.911358679 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer '194'. It is not used by any node and should be removed from the model.
Traceback (most recent call last):
  File "run_onnx.py", line 14, in <module>
    ort_session = onnxruntime.InferenceSession('../models/ctdet_coco_dlav0_1x.onnx')
  File "/home/lsc/anaconda3/envs/CenterNet/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 23, in __init__
    self._load_model()
  File "/home/lsc/anaconda3/envs/CenterNet/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 35, in _load_model
    self._sess.load_model(self._path_or_bytes, providers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(6)
```
In [onnxruntime/Versioning.md](https://github.com/Microsoft/onnxruntime/blob/master/docs/Versioning.md), we can find the information about the compatibility of onnxruntime. So this issue is caused by the incompatibility between the model and onnxruntime. 
The version of Pytorch is 0.4.1, and the onnxruntime is 1.0.0 in my Linux System. I try to upgrade my Pytorch vision to solve the issue. However, after upgrade Pytorch to the newest version and run the code, a new error arises.
```
...
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead. 
```
As indicated [here](https://github.com/pytorch/pytorch/issues/15645), torch.utils.ffi is deprecated in later versions of version 0.4.1.
Another way is down the version on onnxruntime, but I dont know which is applicable. Because in [onnxruntime/Versioning.md](https://github.com/Microsoft/onnxruntime/blob/master/docs/Versioning.md), there is no information about opset version 6 (most versions of ONNX Runtime is support opset higher than version 7).

What should I do? Thank you!

**Comment by CaoWGG** [comment]
@lsccccc 
If you use dlav0 as the backbone, you do not need to compile DCN(deform conv).
Convert to onnx model, only dlav0.py and load_model() are required.

**Comment by liukaigua** [comment]
@CaoWGG Thank you, do you mean if I use dlavo as the backbone, I can just comment the next lines in model.py?
```
from .networks.msra_resnet import get_pose_net
from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
from .networks.resnet_dcn import get_pose_net as get_pose_net_dcn
from .networks.large_hourglass import get_large_hourglass_net
```
I will try it.

**Comment by liukaigua** [comment]
@CaoWGG Successfully run the model, but the onnx output can hardly match the pytorch output.
```
2019-12-15 22:03:29.802718606 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer 'dla_up.ida_2.proj_1.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
2019-12-15 22:03:29.802770597 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer 'dla_up.ida_2.node_3.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
...

AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatch: 99.8%
Max absolute difference: 312.23807
Max relative difference: 34.309364
 x: array([[[[-10.092319, -13.767632, -17.450342, ...,  -8.886379,
           -9.02972 ,  -8.010611],
         [-10.137232, -14.817106, -20.383217, ..., -11.058266,...
 y: array([[[[ -3.771907,  -4.38989 ,  -4.848222, ...,  -4.203885,
           -4.05386 ,  -4.607953],
         [ -4.334212,  -5.200338,  -5.694104, ...,  -5.040788,...
```
the  code is
```
def forward(self, x):
    x = self.base(x)
    x = self.dla_up(x[self.first_level:])
    ret = []
    for head in self.heads:
        ret.append(self.__getattr__(head)(x))
    return ret

net = get_pose_net(34, {'hm':80, 'reg':2, 'wh':2})
net.forward = MethodType(forward, net)
load_model(net, '../models/ctdet_coco_dlav0_1x.pth')

x = torch.randn(1, 3, 512, 512, requires_grad=True)
torch_out = net(x)

print("Run model")
ort_session = onnxruntime.InferenceSession('../models/ctdet_coco_dlav0_1x.onnx')
print("Load OK")
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
    
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)

np.testing.assert_allclose(to_numpy(torch_out[0]), ort_outs[0], rtol=1e-03, atol=1e-05)
print("Exported model has been tested with ONNXRuntime, and the result looks good!")

```

**Comment by liukaigua** [comment]
By adding `net.eval()` before run pytorch model, the models seems to match, however the warnings remain.
```
2019-12-15 22:24:14.418991033 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer 'dla_up.ida_2.proj_1.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
2019-12-15 22:24:14.419039592 [W:onnxruntime:Default, graph.cc:2367 CleanUnusedInitializers] Removing initializer 'dla_up.ida_2.node_3.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
...
Exported model has been tested with ONNXRuntime, and the result looks good!
```

**Comment by caixhstrive** [comment]
using "onnx.export(net, x, onnx_path, export_params=True, verbose = True, opset_version=10)", setting opset_version value equal to 10,  when pytorch==1.5.0, the result is that:

  %512 : Float(1, 256, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%505, %wh.0.weight, %wh.0.bias) # /home/caixh/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
  %513 : Float(1, 256, 256, 256) = onnx::Relu(%512) # /home/caixh/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/functional.py:1061:0
  %514 : Float(1, 2, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%513, %wh.2.weight, %wh.2.bias) # /home/caixh/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
  return (%508, %511, %514)

Run model
Load OK
Exported model has been tested with ONNXRuntime, and the result looks good!

**Comment by caixhstrive** [comment]
using "onnx.export(net, x, onnx_path, export_params=True, verbose = True, opset_version=10)", setting opset_version value equal to 10, when pytorch==1.5.0, the result is that:

%512 : Float(1, 256, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%505, %wh.0.weight, %wh.0.bias) # /home/**/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
%513 : Float(1, 256, 256, 256) = onnx::Relu(%512) # /home/**/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/functional.py:1061:0
%514 : Float(1, 2, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%513, %wh.2.weight, %wh.2.bias) # /home/***/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
return (%508, %511, %514)

Run model
Load OK
Exported model has been tested with ONNXRuntime, and the result looks good!

**Comment by caixh39** [comment]
using "onnx.export(net, x, onnx_path, export_params=True, verbose = True, opset_version=10)", setting opset_version value equal to 10, when pytorch==1.5.0, the result is that:

%512 : Float(1, 256, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%505, %wh.0.weight, %wh.0.bias) # /home/***/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
%513 : Float(1, 256, 256, 256) = onnx::Relu(%512) # /home/***/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/functional.py:1061:0
%514 : Float(1, 2, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%513, %wh.2.weight, %wh.2.bias) # /home/***/anaconda3/envs/centerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py:346:0
return (%508, %511, %514)

Run model
Load OK
Exported model has been tested with ONNXRuntime, and the result looks good!
