### ISSUE TITLE
How did you get the model? Did you train it yourself?

### ISSUE THREAD

**Issue by Edwardmark** [CaoWGG/TensorRT-CenterNet#17]
Hi, man.
Did you train the model by yourself or use the model in https://github.com/Star-Clouds/CenterFace ?
Thanks.

**Comment by CaoWGG** [comment]
I copy the centerface.onnx from centerface repo.

**Comment by Edwardmark** [comment]
@CaoWGG Thanks, man.

**Comment by BobDLA** [comment]
> I copy the centerface.onnx from centerface repo.
@CaoWGG 
The model from origin repo has 1X3X32X32 as input, but, your model has 1X3X1056X1920.
How did you do this change?
