### ISSUE TITLE
CUDA error 77 

### ISSUE THREAD

**Issue by bleakie** [CaoWGG/TensorRT-CenterNet#21]
I got this error(cuda9.0, tensorrt5.1.2):
CUDA error 77 at TensorRT-CenterNet/src/ctdetNet.cpp:163runDet: /TensorRT-CenterNet/src/ctdetNet.cpp:163：void ctdet::ctdetNet::doInference(const void*, void*): 假设 ‘0’ 失败。

**Comment by CaoWGG** [comment]
@bleakie 
1.use netron to check  input shape of .onnx
2.change inputw and inputh in include/ctdetConfig.h

**Comment by bleakie** [comment]
tensorrt version bug， please change to trt5.0, get ok

**Comment by ZeroE04** [comment]
> tensorrt version bug， please change to trt5.0, get ok

no, my version is 5.0, i also get this error....
