### ISSUE TITLE
CUDA error 77 at ctdetNet.cpp:163Assertion failed: 0, file ctdetNet.cpp, line 163

### ISSUE THREAD

**Issue by deep-practice** [CaoWGG/TensorRT-CenterNet#23]

**Comment by KAIIUK** [comment]
I got the same error
Tell me, how did you decide?
CUDA error 700 at /var/host_share/TensorRT-CenterNet/src/ctdetNet.cpp:163runDet: /var/host_share/TensorRT-CenterNet/src/ctdetNet.cpp:163: void ctdet::ctdetNet::doInference(const void*, void*): Assertion `0' failed.
Aborted (core dumped)

**Comment by 17702513221** [comment]
CUDA error 77 at /home/xs/TensorRT-CenterNet/src/ctdetNet.cpp:152CUDA error 77 at /home/xs/TensorRT-CenterNet/src/ctdetNet.cpp:163 total runtime = 0.00754245 ms

**Comment by deep-practice** [comment]
https://github.com/Stephenfang51/CenterNet_TensorRT_CPP
This repo can run smoothly with Tensorrt 5.1
