### ISSUE TITLE
你好，怎么解决这个cmake问题呢？

### ISSUE THREAD

**Issue by Joevaen** [CaoWGG/TensorRT-CenterNet#24]
CMake Error at onnx-tensorrt/CMakeLists.txt:28 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
工程打开的时候出现的，请问怎么解决呢？

**Comment by ElonKou** [comment]
Have you install cuda already?

**Comment by MrLee12138** [comment]
你好，我也遇到了这个问题，请问你是如何解决的呢？

**Comment by Joevaen** [comment]
> 你好，我也遇到了这个问题，请问你是如何解决的呢？
换公司了，好久没用了，有点忘了，不好意思哈
