### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by facerless** [CaoWGG/TensorRT-CenterNet#35]
[ 87%] Building CXX object src/CMakeFiles/ctdet.dir/utils.cpp.o
[ 89%] Linking CXX shared library ../../lib/libctdet.so
collect2: error: ld returned 1 exit status
src/CMakeFiles/ctdet.dir/build.make:238: recipe for target '../lib/libctdet.so' failed
make[2]: *** [../lib/libctdet.so] Error 1
CMakeFiles/Makefile2:476: recipe for target 'src/CMakeFiles/ctdet.dir/all' failed
make[1]: *** [src/CMakeFiles/ctdet.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

can u help me fix this error?

**Comment by 17702513221** [comment]
Can you tell me how to deal with it

**Comment by facerless** [comment]
sudo ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib/libcudart.so
It works for me!&nbsp;
You can try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谢晟"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 上午9:02
收件人: "CaoWGG/TensorRT-CenterNet"<TensorRT-CenterNet@noreply.github.com&gt;; 
抄送: "星空"<573743392@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [CaoWGG/TensorRT-CenterNet] cmake error (#35)




Can you tell me how to deal with it
