### ISSUE TITLE
centerface速度慢？

### ISSUE THREAD

**Issue by sigma-alpha-beta** [CaoWGG/TensorRT-CenterNet#37]
我用笔记本试了下cdet_coco_dla_2x大约是90ms左右，cdet_helmet大约11ms左右，centerface大约90ms，按模型大小centerface应该和helmet差不多大，速度不应差这么多，请问这个可能是什么原因呢，您机子上centerface速度是多少呢？谢谢

**Comment by CaoWGG** [comment]
@guoguangchao 注意一下模型输入图像的大小，helmet的模型输入大小是512,512

**Comment by sigma-alpha-beta** [comment]
好的,非常感谢!
