### ISSUE TITLE
CUDA_CHECK(cudaMemcpyAsync...) cost too much time.

### ISSUE THREAD

**Issue by ElonKou** [CaoWGG/TensorRT-CenterNet#43]
Thanks  for your great work. I have convert the model from onnx. When I print the time of the whole process of Inference , It seems some unexpected things happened, the `cudaMemcpyAsync` cost about 23 ms.
```bash
user@ubuntu:~/CPP/27.CENTERNET/TensorRT-CenterNet$ ./runDet -e model/ctdet_coco_dla_2x.engine -i test.jpg 
deserializing
WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
check: 23.8991 ms
 total runtime = 35.4601 ms 
```
The total runtime was print from ctdetNet.printTime(), and I add time check function in 
https://github.com/CaoWGG/TensorRT-CenterNet/blob/f949252e37b51e60f873808f46d3683f15735e79/src/ctdetNet.cpp#L163
```c++
auto t_start = chrono::high_resolution_clock::now();
CUDA_CHECK(cudaMemcpyAsync(outputData, cudaOutputBuffer, outputBufferSize, cudaMemcpyDeviceToHost, mCudaStream));
auto  t_end = chrono::high_resolution_clock::now();
float cost_t = chrono::duration<float, milli>(t_end - t_start).count();
cout << "check: " << cost_t << " ms" << endl;
```
My environment :
> OS: ubuntu 16.04
CUDA:10.0
CUDNN:7.5
tensorRT:5.1

Could you please show your `cudaMemcpyAsync` cost time or the way to solve this question? Thank you very much.

**Comment by CaoWGG** [comment]
you can try this:
`
float num_det = 0;

CUDA_CHECK(cudaMemcpy(&num_det, cudaOutputBuffer, sizeof(float), cudaMemcpyDeviceToHost));

CUDA_CHECK(cudaMemcpy(outputData, cudaOutputBuffer, sizeof(float) + num_det*sizeof(Detection), cudaMemcpyDeviceToHost));
 `

**Comment by ElonKou** [comment]
@CaoWGG Thank you very much , It seems work when I replace `cudaMemcpy` into `cudaMemcpyAsync` :+1:
