### ISSUE TITLE
createParser is not member of nvonnxparser

### ISSUE THREAD

**Issue by HappyKerry** [CaoWGG/TensorRT-CenterNet#6]
TensorRT 4 cuda8.0 
not support?

**Comment by CaoWGG** [comment]
@HappyKerry 
I only tested tensorrt5.

**Comment by HappyKerry** [comment]
@CaoWGG
Would you like to test it in TensorRT4? 
Thanks

**Comment by CaoWGG** [comment]
@HappyKerry 
Sorry, my GPU is public. You can install tensorrt5 on your device。
