### ISSUE TITLE
cthelmet 模型来源

### ISSUE THREAD

**Issue by zhongwenkun886** [CaoWGG/TensorRT-CenterNet#68]
hi，您好，请问您项目中的cthelmet的模型是怎么训练出来的？谢谢

**Comment by CaoWGG** [comment]
@zhongwenkun886 
您好，模型是由  https://github.com/CaoWGG/Mobilenetv2-CenterNet +  https://github.com/xingyizhou/CenterNet  训出来的

**Comment by zhongwenkun886** [comment]
非常感谢。再请教下，您的训练数据集事公开的数据集吗？

**Comment by CaoWGG** [comment]
@zhongwenkun886 
coco+voc 数据集中的行人参与了训练。
部分安全帽的数据来自这里(https://www.datafountain.cn )，不过目前应该下不到了。
还有部分安全帽数据是不是公开的数据集。

**Comment by zhongwenkun886** [comment]
谢谢指教
