### ISSUE TITLE
The result is wrong for helmet detection

### ISSUE THREAD

**Issue by Jumponthemoon** [CaoWGG/TensorRT-CenterNet#71]
Hi,i succesfully built the engine for the helmet detection as the command you provide:
`./buildEngine -i model/ctdet_helmet.onnx -o model/ctdet_helmet.engine -m 0`
The output shows it runs well:

>
Input filename:   model/ctdet_helmet.onnx
ONNX IR version:  0.0.3
Opset version:    6
Producer name:    pytorch
Producer version: 0.3
Domain:           
Model version:    0
Doc string:       

Begin building engine...
End building engine...
save  model/ctdet_helmet.engine

But when i run the detection,the result output a full black image.How to solve?

**Comment by sailyung** [comment]
after modified /include/ctdetConfig.h, need to re cmake build

**Comment by Jumponthemoon** [comment]
> after modified /include/ctdetConfig.h, need to re cmake build

Works for me.Thanks!
