### ISSUE TITLE
the difference between before and after model trans.

### ISSUE THREAD

**Issue by KevenLee** [CaoWGG/TensorRT-CenterNet#73]
Suppose pytorch model as A , it's output as AC , tensorRT model as B , it's output as BC. 

Then, I observed that there is a big gap between the output layers AC and BC , although the final detection result looks normal. For example, model A heatmap hm[i, j] = 0.75, model B heatmap hm[i, j] = 0.53, although the values of a and b are very different, they are both local maximums. So , detection results seems normal.
What do you think of this problem?
Thanks.

**Comment by janismdhanbad** [comment]
Hi, could you please let me know how you extracted hm values? Thanks

**Comment by KevenLee** [comment]
> Hi, could you please let me know how you extracted hm values? Thanks

I‘m very sorry that, I do something wrong with feature extraction. I have fixed it

**Comment by Jinreejing** [comment]
> with feature extraction. I ha

hello, could you please let me know is there a dcnv2 op in your model?

**Comment by Jinreejing** [comment]
> > with feature extraction. I ha
> 
> hello, could you please let me know is there a dcnv2 op in your model?

@KevenLee
