### ISSUE TITLE
Accuracy not even half as the original model

### ISSUE THREAD

**Issue by ashuezy** [CaoWGG/TensorRT-CenterNet#8]
Just ran your code with float32 calibration on the video. The accuracy is not good. Have you modified the original code is some other way ?

**Comment by CaoWGG** [comment]
Did you test the accuracy ?

**Comment by ashuezy** [comment]
Yes on multiple camera streams.

**Comment by ashuezy** [comment]
@CaoWGG Any thoughts to improve accuracy ?

**Comment by CaoWGG** [comment]
sorry, i dont know how you get acc. You can add my wechat: 15706290529  to talk

**Comment by CaoWGG** [comment]
@ashuezy sorry, i dont know how you get acc. You can add my wechat: 15706290529 to talk

**Comment by ashuezy** [comment]
I don't know whether you test your code or not but I am getting the following output:
![Screenshot from 2019-12-18 12-58-22](https://user-images.githubusercontent.com/31314950/71065005-4c788800-2196-11ea-9093-ec2549f5311b.png)

**Comment by CaoWGG** [comment]
@ashuezy 
you need to config (include/ctdetConfig.h).
if you run centerface.onnx. (for centerface)
```
    //cthelmet
    // static int classNum = 2 ;
    // static float mean[]= {0.485,0.456,0.406};
    // static float std[] = {0.229,0.224,0.225};
    // static char *className[]= {(char*)"person",(char*)"helmet"};
    //ctface
     static int classNum = 1 ;
     static float mean[]= {0,0,0};
     static float std[] = {1,1,1};
     static char *className[]= {(char*)"face"};
```
if you run ctdet_helmet.onnx.  (for centernet)
```
    //cthelmet
    static int classNum = 2 ;
    static float mean[]= {0.485,0.456,0.406};
    static float std[] = {0.229,0.224,0.225};
    static char *className[]= {(char*)"person",(char*)"helmet"};
    //ctface
    // static int classNum = 1 ;
    // static float mean[]= {0,0,0};
    // static float std[] = {1,1,1};
    // static char *className[]= {(char*)"face"};
```

**Comment by ashuezy** [comment]
This fixed the issue.

- This model only works with very high resolution images i.e face size must be greater than 150,150
- Rarely works on sidefaces.
- Lots of misses.

The original model is very accurate. It is comparable to MTCNN. This however is nowhere near.

**Comment by CaoWGG** [comment]
@ashuezy 
Tensorrt5 does not support dynamic shape.
For Centerface, you can change the input shape to  a lager shape, such as 640×640,1280×1280,1920×1920. Maybe you can get better results.
(My current implementation only support input_w == input_w.)

**Comment by ashuezy** [comment]
I am closing this issue as there is a difference in accuracy because of the implementation.
