### ISSUE TITLE
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)

### ISSUE THREAD

**Issue by ChunfengMI** [CaoWGG/TensorRT-CenterNet#90]
wb@dgx-station:~/TensorRT-CenterNet/build$ cmake .. && makeCMake Error at /home/wb/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/wb/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/wb/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  onnx-tensorrt/CMakeLists.txt:111 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/wb/TensorRT-CenterNet/build/CMakeFiles/CMakeOutput.log".
See also "/home/wb/TensorRT-CenterNet/build/CMakeFiles/CMakeError.log".
wb@dgx-station:~/TensorRT-CenterNet/build$ protoc --version
libprotoc 3.1.0
wb@dgx-station:~/TensorRT-CenterNet/build$ whereis protoc
protoc: /usr/local/protobuf/bin/protoc
wb@dgx-station:~/TensorRT-CenterNet/build$ which protoc
/usr/local/protobuf/bin/protoc

I am using TensorRT-7.0.0.11 and cuda 10.2. Looking forward to your reply, thx!

**Comment by Duanexiao** [comment]
@ChunfengMI Hello,could you paste your detail solve method?I met the same question

**Comment by ChunfengMI** [comment]
> 
> 
> @ChunfengMI Hello,could you paste your detail solve method?I met the same question
Unfortunately, we haven't solved it yet.

**Comment by Duanexiao** [comment]
> > @ChunfengMI Hello,could you paste your detail solve method?I met the same question
> > Unfortunately, we haven't solved it yet.

after yum install protobuf-compiler, move the lib and include ,bin files into /usr/lib;/usr/include;/usr/bin directory, error dispeared
